name: CI

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'Tweak.xm'        # 修正：应为 Tweak.xm，而不是 Tweak.x
      - 'control'
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Use Theos Setup Action
        uses: axs66/theos-action@main

      # ✅ 双重清理防缓存残留
      - name: Clean Theos cache and previous build
        run: |
          make clean || true
          rm -rf .theos
          rm -f ${{ github.workspace }}/packages/*.deb

      # ✅ 可选：禁用 VLA 警告，防止编译器误报
      - name: Append extra CFLAGS
        run: echo 'ADDITIONAL_CFLAGS += -Wno-vla-cxx-extension -Wno-gnu-variable-sized-type-not-at-end' >> Makefile

      - name: Build DEB (rootless + roothide)
        run: |
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - name: List generated DEBs
        run: ls -lh ${{ github.workspace }}/packages

      - name: Create GitHub Release
        run: |
          VERSION=$(date +v%Y%m%d%H%M)
          gh release create $VERSION ${{ github.workspace }}/packages/*.deb --title "Combined $VERSION" --notes "自动构建 .deb 安装包"
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      - name: Upload DEB to workflow artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Combined
          path: ${{ github.workspace }}/packages/*.deb
