name: Build CombinedTweak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        echo "$HOME/theos/bin" >> $GITHUB_PATH
        
    - name: Setup iOS SDK
      run: |
        curl -L https://github.com/theos/sdks/archive/master.zip -o sdks.zip
        unzip -q sdks.zip
        mkdir -p $HOME/theos/sdks
        mv sdks-master/*.sdk $HOME/theos/sdks/
        
    - name: Install libGCUniversal
      run: |
        git clone https://github.com/MrGcGamer/LibGcUniversal.git libgcuniversal
        cd libgcuniversal
        make package install
        
    - name: Build CombinedTweak
      run: |
        cd CombinedTweak
        make clean
        make package
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CombinedTweak-deb
        path: CombinedTweak/*.deb
